# Generated by Django 5.0.1 on 2026-02-04 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputereport',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.bookingsession'),
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['user', 'status'], name='booking_ses_user_id_944c78_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['spot_id'], name='booking_ses_spot_id_1d45c6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['scheduled_start_time', 'scheduled_end_time'], name='booking_ses_schedul_6a7af1_idx'),
        ),
        migrations.AddIndex(
            model_name='disputereport',
            index=models.Index(fields=['booking'], name='dispute_rep_booking_60a277_idx'),
        ),
        migrations.AddIndex(
            model_name='disputereport',
            index=models.Index(fields=['status'], name='dispute_rep_status_89e018_idx'),
        ),
    ]
