# Generated by Django 5.0.1 on 2026-02-04 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialParkingFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('facility_type', models.CharField(choices=[('mall', 'Mall'), ('office', 'Office'), ('apartment', 'Apartment'), ('hospital', 'Hospital'), ('airport', 'Airport'), ('stadium', 'Stadium')], max_length=20)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flat_day_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('has_valet_service', models.BooleanField(default=False)),
                ('has_car_wash', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commercial_parking_facilities',
            },
        ),
        migrations.CreateModel(
            name='CommercialParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('slot_type', models.CharField(choices=[('regular', 'Regular'), ('compact', 'Compact'), ('ev', 'EV Charging'), ('handicap', 'Handicap'), ('vip', 'VIP')], default='regular', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commercial_parking_slots',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('spot_type', models.CharField(choices=[('mall', 'Mall Parking'), ('private_driveway', 'Private Driveway'), ('office', 'Office'), ('apartment', 'Apartment'), ('hospital', 'Hospital'), ('airport', 'Airport'), ('stadium', 'Stadium')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_cctv', models.BooleanField(default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('has_insurance', models.BooleanField(default=False)),
                ('has_valet_service', models.BooleanField(default=False)),
                ('has_car_wash', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=False)),
                ('has_water_access', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('access_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_spots',
            },
        ),
        migrations.CreateModel(
            name='PrivateParkingListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('description', models.TextField()),
                ('total_slots', models.IntegerField(default=1)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=40.0, max_digits=8)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=300.0, max_digits=8)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=3000.0, max_digits=8)),
                ('flat_full_booking_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('auto_accept_bookings', models.BooleanField(default=False)),
                ('instant_booking_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_cctv', models.BooleanField(default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=False)),
                ('has_water_access', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('max_booking_duration', models.CharField(choices=[('hourly', 'Hourly Only'), ('daily', 'Up to 1 Day'), ('weekly', 'Up to 1 Week'), ('monthly', 'Up to 1 Month'), ('unlimited', 'Unlimited')], default='unlimited', max_length=20)),
                ('suggested_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'private_parking_listings',
            },
        ),
        migrations.CreateModel(
            name='PrivateParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'private_parking_slots',
            },
        ),
    ]
