# Generated by Django 5.0.1 on 2026-02-04 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialparkingfacility',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialparkingslot',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.commercialparkingfacility'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateparkinglisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateparkingslot',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.privateparkinglisting'),
        ),
        migrations.AddIndex(
            model_name='commercialparkingslot',
            index=models.Index(fields=['facility', 'floor'], name='commercial__facilit_68e430_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commercialparkingslot',
            unique_together={('facility', 'slot_number')},
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['latitude', 'longitude'], name='parking_spo_latitud_7df364_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['spot_type'], name='parking_spo_spot_ty_a142a4_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['is_occupied'], name='parking_spo_is_occu_e10b93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privateparkingslot',
            unique_together={('listing', 'slot_number')},
        ),
    ]
